# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: N:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager.xci
# IP: The module: 'ClockManager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: N:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager.xci
# IP: The module: 'ClockManager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: n:/GitHub/Y3-VHDL/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.srcs/sources_1/ip/ClockManager/ClockManager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockManager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
