webtalk_init -webtalk_dir D:/University/ENG631 - VHDL and FPGA/VHDL Source/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.sim/sim_1/behav/xsim/xsim.dir/T16_M2_Random_Number_generator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb  6 17:13:57 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3fa4a28d-915d-4bcc-b1fd-f92ae4ee6fbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1ed7250cc3c04c02bf8a24763c395645" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "106432200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2570289893 -regid "" -xml D:/University/ENG631 - VHDL and FPGA/VHDL Source/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.sim/sim_1/behav/xsim/xsim.dir/T16_M2_Random_Number_generator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/University/ENG631 - VHDL and FPGA/VHDL Source/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.sim/sim_1/behav/xsim/xsim.dir/T16_M2_Random_Number_generator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/University/ENG631 - VHDL and FPGA/VHDL Source/ENG631_CW1_T16_Milestone2/ENG631_CW1_T16_Milestone2.sim/sim_1/behav/xsim/xsim.dir/T16_M2_Random_Number_generator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
