# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/T16_M1.xdc

# IP: D:/University/VHDL/Y3-VHDL/ENG631_CW1_T16/ENG631_CW1_T16.srcs/sources_1/ip/ClockManager/ClockManager.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockManager || ORIG_REF_NAME==ClockManager} -quiet] -quiet
