set_property PACKAGE_PIN W5         [get_ports i_C100Mhz]
set_property IOSTANDARD LVCMOS33    [get_ports i_C100Mhz]

create_clock -add -period 10.000 -name C100Mhz_pin -waveform {0.000 5.000} [get_ports i_C100Mhz]


set_property PACKAGE_PIN V17        [get_ports {i_Fast}]
set_property IOSTANDARD LVCMOS33    [get_ports {i_Fast}]

set_property PACKAGE_PIN U16        [get_ports {o_LEDs[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[0]}]
set_property PACKAGE_PIN E19        [get_ports {o_LEDs[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[1]}]
set_property PACKAGE_PIN U19        [get_ports {o_LEDs[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[2]}]
set_property PACKAGE_PIN V19        [get_ports {o_LEDs[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[3]}]
set_property PACKAGE_PIN W18        [get_ports {o_LEDs[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[4]}]
set_property PACKAGE_PIN U15        [get_ports {o_LEDs[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[5]}]
set_property PACKAGE_PIN U14        [get_ports {o_LEDs[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[6]}]
set_property PACKAGE_PIN V14        [get_ports {o_LEDs[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[7]}]
set_property PACKAGE_PIN V13        [get_ports {o_LEDs[8]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[8]}]
set_property PACKAGE_PIN V3         [get_ports {o_LEDs[9]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[9]}]
set_property PACKAGE_PIN W3         [get_ports {o_LEDs[10]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[10]}]
set_property PACKAGE_PIN U3         [get_ports {o_LEDs[11]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[11]}]
set_property PACKAGE_PIN P3         [get_ports {o_LEDs[12]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[12]}]
set_property PACKAGE_PIN N3         [get_ports {o_LEDs[13]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[13]}]
set_property PACKAGE_PIN P1         [get_ports {o_LEDs[14]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[14]}]
set_property PACKAGE_PIN N1         [get_ports {o_LEDs[15]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_LEDs[15]}]


set_property PACKAGE_PIN W7         [get_ports {o_SegmentCathodes[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[6]}]
set_property PACKAGE_PIN W6         [get_ports {o_SegmentCathodes[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[5]}]
set_property PACKAGE_PIN U8         [get_ports {o_SegmentCathodes[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[4]}]
set_property PACKAGE_PIN V8         [get_ports {o_SegmentCathodes[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[3]}]
set_property PACKAGE_PIN U5         [get_ports {o_SegmentCathodes[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[2]}]
set_property PACKAGE_PIN V5         [get_ports {o_SegmentCathodes[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[1]}]
set_property PACKAGE_PIN U7         [get_ports {o_SegmentCathodes[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentCathodes[0]}]
set_property PACKAGE_PIN V7         [get_ports {o_SegmentDP}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentDP}]
set_property PACKAGE_PIN U2         [get_ports {o_SegmentAnodes[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentAnodes[0]}]
set_property PACKAGE_PIN U4         [get_ports {o_SegmentAnodes[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentAnodes[1]}]
set_property PACKAGE_PIN V4         [get_ports {o_SegmentAnodes[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentAnodes[2]}]
set_property PACKAGE_PIN W4         [get_ports {o_SegmentAnodes[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {o_SegmentAnodes[3]}]


set_property PACKAGE_PIN U18        [get_ports {i_Reset}]
set_property IOSTANDARD LVCMOS33    [get_ports {i_Reset}]


set_property BITSTREAM.GENERAL.COMPRESS TRUE    [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4    [current_design]
set_property CONFIG_MODE SPIx4                  [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33    [current_design]

set_property CONFIG_VOLTAGE 3.3                 [current_design]
set_property CFGBVS VCCO                        [current_design]